name: 'Terraform'

on:
  push:
    paths: [ "iac-manifest" , "iac-eks" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init Kubernetes
      working-directory: iac-manifest
      run: terraform init

    - name: Terraform Init AWS EKS
      working-directory: iac-eks
      run: terraform init

    - name: Terraform Format Kubernetes
      working-directory: iac-manifest
      run: terraform fmt -check

    - name: Terraform Format AWS EKS
      working-directory: iac-eks
      run: terraform fmt -check

    - name: Terraform Plan Kubernetes
      working-directory: iac-manifest
      run: terraform plan -input=false

    - name: Terraform Plan AWS EKS
      working-directory: iac-eks
      run: terraform plan -input=false

    - name: Terraform Apply Kubernetes
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: iac-manifest
      run: terraform apply -auto-approve -input=false

    - name: Terraform Apply AWS EKS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: iac-eks
      run: terraform apply -auto-approve -input=false
